apiVersion: v1
kind: Service
metadata:
  name: finapp-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # optional fixed port for local testing
  selector:
    app: finapp